package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/ij4l/foodCatalog/graph/model"
)

// CreateMenu is the resolver for the createMenu field.
func (r *mutationResolver) CreateMenu(ctx context.Context, input *model.NewMenu) (*model.Menu, error) {
	mm, err := r.MenuHandler.InsertMenu(input)
	if err != nil {
		return nil, err
	}

	return mm, nil
}

// ListMenu is the resolver for the listMenu field.
func (r *queryResolver) ListMenu(ctx context.Context) ([]*model.Menu, error) {
	mm, err := r.MenuHandler.FindAll()
	if err != nil {
		return nil, err
	}

	return mm, nil
}

// Menu is the resolver for the menu field.
func (r *queryResolver) Menu(ctx context.Context, id *int) (*model.Menu, error) {
	mm, err := r.MenuHandler.FindById(1)
	if err != nil {
		return nil, err
	}

	return mm, nil
}
