// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO
  auth (email, password)
VALUES
  ($1, $2)
`

type InsertUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.Email, arg.Password)
	return err
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT
  id,
  email,
  password,
  created_at,
  updated_at
FROM
  auth
WHERE
  email = $1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (Auth, error) {
	row := q.db.QueryRow(ctx, selectUserByEmail, email)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
