// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID        int32              `json:"id"`
	Nip       pgtype.Text        `json:"nip"`
	Name      pgtype.Text        `json:"name"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Menu struct {
	ID          int32              `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Category    pgtype.Text        `json:"category"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Int4        `json:"price"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID         int32              `json:"id"`
	EmployeeID pgtype.Int4        `json:"employee_id"`
	MenuID     pgtype.Int4        `json:"menu_id"`
	Quantity   pgtype.Int4        `json:"quantity"`
	Total      pgtype.Int4        `json:"total"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
